### ISSUE TITLE
Add installation details at README

### ISSUE THREAD

**Issue by ppKrauss** [ThomasBarris/populationWDvsOSM#3]
Hi, good project!

A suggestion to incentive others (even dummy users) to use: add a complete example of installation and deploy. Example of sequence at Linux terminal:

1. `git clone https://github.com/ThomasBarris/populationWDvsOSM.git` and `cd  populationWDvsOSM`.
2. `pip install SPARQLWrapper`
3. `pip install overpass`
4. `python3 WdOSMpop.py` 

But we need to check if all here. In this case, at UBUNTU 16 will be an error,
```
Traceback (most recent call last):
  File "WdOSMpop.py", line 4, in <module>
    import overpass
ImportError: No module named 'overpass'
```
-----

When running at UBUNTU 18 LTS, after `nano WdOSMpop.py` (changing `html_file = ...`  to a valid one) and `python WdOSMpop.py`, error:
```
  File "WdOSMpop.py", line 29
SyntaxError: Non-ASCII character '\xc3' in file WdOSMpop.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
So deleted the line with UTF8 error, `# ThÃ¼ringen .. `. Them `python WdOSMpop.py`, new error:
```
File "WdOSMpop.py", line 45
    print('<!DOCTYPE html>', file=preview_html)
                                 ^
SyntaxError: invalid syntax
```

**Comment by ThomasBarris** [comment]
Can you please retry? I have modified the code a bit and added the installation as per your recommendation. If you still have issues with Ubuntu 16, can you please reinstall the overpass library with  `pip install --upgrade --force-reinstall overpass` ? I am using Ubuntu 16 and it works. You may want to check the overpass version with `pip freeze | grep overpass`. It should return `overpass==0.6.0`

**Comment by ppKrauss** [comment]
Hi @ThomasBarris , thanks.  I try  your suggestion and seems better (same `overpass==0.6.0`)... But now I  using a direct script with overpass, [see help.openstreetmap 65023/65035](https://help.openstreetmap.org/questions/65023/bbox-of-a-relation-by-its-id-api-to-obtan-it/65035)... Abandoning script, but using your main idea.


PS: the test was difficult also by UTF8 errors, I used `import sys`, `reload(sys)`, `sys.setdefaultencoding('utf8')`. To avoid repeated `print(x,file=)` and STDOUT option,  used something as `sys.stdout = open('output.txt','wt')` before single print.

**Comment by ThomasBarris** [comment]
Python and UTF8 errors are responsible for half of my grey hair ;) Good luck
